### ISSUE TITLE
Is multiple client supported by Mitsubishi PLC?

### ISSUE THREAD

**Issue by arkypita** [SatohNorio/McProtocol#2]
I apologize if I ask for information here, but I have not found any other places to talk about communication with Mitsubishi PLC.

I have developed a C # program that communicates with a Misubishi PLC, using your code (a fork from https://github.com/blueskit/MitsubishiPlcProtocol).

What happens is that if I connect two instances of this program, the first instance connects and can read the data from the PLC, while the second instance connects but does not get the response packets to its own read requests. The second instance is able to complete the reading only when the first instance is disconnected.

It seems that the PLC does not support two connected readers simultaneously. Could it be? Is there any confirmation of this problem in some documentation? I could not find anything!

Thanks for any kind of support. Diego

**Comment by SatohNorio** [comment]
I did't test that using multi instances of PLC, but It might not work properly.
Because TCP sockets can't be created by two same ports.
If you want to use two connections, you need to define different port in PLC and connect different port.

I hope your program become better.

**Comment by arkypita** [comment]
thanks
